src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="date")
     */
    private $publishDate;

    /**
     * @ORM\Column(type="string", length=999999999, nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $metadescription;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titleH1;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $slug = new Slugify();
        $this->slug = $slug->slugify($title);
        $this->title = $title;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publishDate;
    }

    public function setPublishDate(\DateTimeInterface $publishDate): self
    {
        $this->publishDate = $publishDate;

        return $this;
    }

    public function getContent(): ?string
    {
     return $this->content;
    }

    public function setContent(?string $content): self
    {
       $this->content = $content;

        return $this;
    }

    public function getDisplayContent(){
        $pattern = '/h1/i';
        $replacement = 'h2';
        return preg_replace($pattern, $replacement, $this->content);
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getMetadescription(): ?string
    {
        return $this->metadescription;
    }

    public function setMetadescription(string $metadescription): self
    {
        $this->metadescription = $metadescription;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }


    public function __toString(){
        return $this->title;
    }

    public function getTitleH1(): ?string
    {
        return $this->titleH1;
    }

    public function setTitleH1(string $titleH1): self
    {
        $this->titleH1 = $titleH1;

        return $this;
    }

}

src/Controller/MhaController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Kernel;
use App\Entity\Commande;
use App\Repository\BlogRepository;
use App\Service\BlogsService;
use App\Service\ClientService;
use App\Service\ImageService;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Icamys\SitemapGenerator\SitemapGenerator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Mail;


class MhaController extends AbstractController
{

    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        return $this->render('mha/pages/home.html.twig', [
        ]);
    }

    /**
     * @Route("/confidentialite", name="Politique de confidentialité")
     */
    public function confidentialite()
    {

        return $this->render('mha/pages/rgpd.html.twig', [
        ]);
    }

    /**
     * @Route("/cgu", name="CGU")
     */
    public function CGU()
    {

        return $this->render('mha/pages/CGU.html.twig', [
            'light' => true
        ]);
    }

    /**
     * @Route("/cgv", name="CGV")
     */
    public function CGV()
    {

        return $this->render('mha/pages/CGV.html.twig', [
            'light' => true
        ]);
    }

    /**
     * @Route("/imageSandbox", name="imageSandbox")
     */
    public function imageSandbox()
    {
        return $this->render('mha/dragAndDropSandbox.html.twig', [
            'metaDescription' => "a simple drag and drop images sandbox",
            'title' => 'Drag it, Drop it, Copy it!'
        ]);
    }

    /**
     * @Route("/xhr/uploadImage", name="uploadImage")
     */
    public function uploadImage(Request $request, Kernel $kernel)
    {
        $uploadDirectory = 'uploads/embedImage/';
        $path = $kernel->getProjectDir() . '/public/' . $uploadDirectory;
        echo($_FILES['file']['name']);
        $image = $path . basename($_FILES['file']['name']);
        if (move_uploaded_file($_FILES['file']['tmp_name'], $image)) {
            echo "File is valid, and was successfully uploaded.\n";
        } else {
            echo "Possible file upload attack!\n";
        }
        return $this->render('blank.html.twig');
    }

    /**
     * @Route("/blog/{slug}", methods = "get", name="showBlog")
     */
    public function showBlog($slug, BlogRepository $blogRepository)
    {
        $blogs = $blogRepository->findAll();
        $blog = $blogRepository->findOneBy(['slug' => $slug]);

        if (!$blog) {
            return $this->render('bundles/TwigBundle/Exception/error404.html.twig');
        } else {
            return $this->render('mha/pages/blog.html.twig', [
                    'blog' => $blog,
                    'blogs' => $blogs]
            );
        }


    }




}

templates/mha/CGV.html.twig
{% extends('mha/fullwidth-base.html.twig') %}
{% block pageContent %}


    <div class="entry-content">

        <br>
        <h1 style="text-align:center">CONDITIONS GÉNÉRALES</h1>
        <br>


        <div class="container">
            <div class="text-center">
                <h3>Les présentes conditions générales régissent l'utilisation de ce site mha-vtc, fr. Ce site appartient et est
                    géré par Mukhtar Hussein Abdi. En utilisant ce site, vous indiquez que vous avez lu et compris les
                    conditions d'utilisation et que vous acceptez de les respecter en tout temps.</h3>
                <h3>Type de site : réservation VTC</h3>
            </div>
            <br>

            <h2>Propriété intellectuelle</h2>
            <p>Tout contenu publié et mis à disposition sur ce site est la propriété de Mukhtar Hussein Abdi et de ses
                créateurs. Cela comprend, mais n'est pas limité aux images, textes, logos, documents, fichiers
                téléchargeables et tout ce qui contribue à la composition de ce site.</p>
            <h2>Restrictions d'âge</h2>
            <p>L'âge minimum pour utiliser ce site est de 18 ans. Les utilisateurs conviennent qu'en utilisant notre site,
                ils ont plus de 18 ans Nous n'assumons aucune responsabilité juridique pour les fausses déclarations
                sur l'âge.</p>

            <h2>Utilisation acceptable</h2>
            <p>En tant qu'utilisateur, vous acceptez d'utiliser notre site légalement et de ne pas utiliser ce site pour des
                fins illicites, à savoir :</p>
            <ul>
                <li>Violer les droits des autres utilisateurs du site</li>
                <li>Violer les droits de propriété intellectuelle des propriétaires du site ou de tout tiers au site</li>
                <li>Pirater le compte d’un autre utilisateur du site</li>
                <li>Agir de toute façon qui pourrait être considérée comme frauduleuse</li>
                <li>Réserver une course sans avoir l'intention de l'effectuer et de la régler</li>
            </ul>
            <p>Si nous estimons que vous utilisez ce site illégalement ou d'une manière qui viole les conditions
                d'utilisation acceptable ci-dessus, nous nous réservons le droit de limiter, suspendre ou résilier votre
                accès à ce site. Nous nous réservons également le droit de prendre toutes les mesures juridiques
                nécessaires pour vous empêcher d'accéder à notre site.</p>

            <h2>Garanties</h2>
            <ol>
                <li>Double confirmations et recontacte dans Les plus bref délais</li>
                <li>Service de qualité</li>
            </ol>

            <h2>Limitation de responsabilité</h2>
            <p>Mukhtar Hussein Abdi ou l'un de ses employés sera tenu responsable de tout problème découlant de ce
                site. Néanmoins, Mukhtar Hussein Abdi et ses employés ne seront pas tenus responsables de tout
                problème découlant de toute utilisation irrégulière de ce site.</p>

            <h2>Indemnité</h2>
            <p>En tant qu'utilisateur, vous indemnisez par les présentes Mukhtar Hussein Abdi de toute responsabilité,
                de tout coût, de toute cause d'action, de tout dommage ou de toute dépense découlant de votre
                utilisation de ce site ou de votre violation de l'une des dispositions énoncées dans le présent document.</p>

            <h2>Lois applicables</h2>
            <p>Ce document est soumis aux lois applicables en France et vise à se conformer à ses règles et
                règlements nécessaires. Cela inclut la réglementation à l'échelle de l'UE énoncée dans le RGPD.</p>

            <h2>Divisibilité</h2>
            <p>Si, à tout moment, l'une des dispositions énoncées dans le présent document est jugée incompatible ou
                invalide en vertu des lois applicables, ces dispositions seront considérées comme nulles et seront
                retirées du présent document. Toutes les autres dispositions ne seront pas touchées par les lois et le
                reste du document sera toujours considéré comme valide.</p>

            <h2>Modifications</h2>
            <p>Ces conditions générales peuvent être modifiées de temps à autre afin de maintenir le respect de la loi
                et de refléter tout changement à la façon dont nous gérons notre site et la façon dont nous nous
                attendons à ce que les utilisateurs se comportent sur notre site. Nous recommandons à nos utilisateurs
                de vérifier ces conditions générales de temps à autre pour s'assurer qu'ils sont informés de toute mise à
                Jour. Au besoin, nous informerons les utilisateurs par courriel des changements apportés à ces
                conditions ou nous afficherons un avis sur notre site.</p>

            <h2>Contact</h2>
            <p class="text-center">Veuillez communiquer avec nous si vous avez des questions ou des préoccupations. Nos coordonnées

                sont Les suivantes :</p>
            <p> <span class="fa fa-telephone"></span> 06 69 97 83 05</p>
            <p> <span class="fa-fa-mail"></span> chauffeur@mha-vtc.fr</p>
            <p> <span class=" fa fa-mail"> </span>mhavtc@gmail.com</p>

            <p style="float: right">Date d'entrée en vigueur : le 22 août 2020.</p>
        </div>

        <p>&nbsp;</p>
    </div>
{% endblock %}

templates/mha/blog.html.twig
{% extends('mha/fullwidth-base2-light.html.twig') %}
{% block stylesheet %}
h2{
    font-size: 34px;
    letter-spacing: 0;
    line-height: 38px;
    margin-bottom: 12px;
    margin-top: 8px;
    color: #1f1f1f;
    text-align:center;
    }
    .content{
    font-size: 1rem;
    font-style: normal;
    font-weight: 400;
    text-transform: none;
    line-height: 1.7;
    letter-spacing: 0;
    color: #777777;
    font-family: "Poppins", sans-serif;
    }
    figcaption{
    padding-top: 10px;
    text-align:center;
    }
    blockquote{
    border-left: 3px solid #2250fc;
    font-size: 20px;
    padding: 10px 20px;
    margin: 0 0 20px;
    }
    .content>ul,.content>ol
    {
    padding-left : 30px;
    }
    figure>img{
    width: 100%;
    height: auto;
    }

{% endblock %}
{% block pageContent %}
    <section id="page-content" class="sidebar-right" style="transform: none;">
        <div class="container" style="transform: none;">
            <div class="row" style="transform: none;">
                <!-- content -->
                <div class="content col-lg-9">
                    <!-- Blog -->
                    <div id="blog" class="single-post">
                        <!-- Post single item-->
                        <div class="post-item">
                            <div class="post-item-wrap">
                                <div class="post-image" style="text-align: center">
                                    <a href="#">
                                        <img alt="" src="{{ asset(blog.image) }}" style="max-height: 440px; width: auto ;max-width: 100%; margin: 0 auto">
                                    </a>
                                </div>
                                <div class="post-item-description">
                                    <h1 style="text-align: center">{{blog.titleh1 | capitalize()}}</h1>
                                    <div class="post-meta">
                                    </div>

                                    {{ blog.displayContent | raw}}

                                </div>
                                <section id="contact">
                                    <div class="container">
                                        <div class="heading-text text-center heading-section">
                                            <h4 style="font-size: 38px;line-height: 40px;"> Quoi qu'il en soit, optez pour la sécurité et le confort </h4>
                                            <h4> Choisissez MHA-VTC !</h4>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12 text-center">
                                                <a class="btn" href="{{ path('reservation') }}"> Réserver une course </a>
                                            </div>
                                        </div>
                                    </div>
                                </section>
                            </div>
                        </div>

                        <!-- end: Post single item-->
                    </div>
                </div>
                <!-- end: content -->
                <!-- Sidebar-->
                <div class="sidebar sticky-sidebar col-lg-3" style="position: relative; overflow: visible; box-sizing: border-box; min-height: 3032px;">
                    <!--widget newsletter-->

                    <!--end: widget newsletter-->
                    <!--Tabs with Posts-->

                    <!--End: Tabs with Posts-->
                    <!-- Twitter widget -->

                    <!-- end: Twitter widget-->
                    <!--widget tags -->

                    <!--end: widget tags -->
                    <div class="theiaStickySidebar" style="padding-top: 0px; padding-bottom: 1px; position: fixed; transform: translateY(-179.73px); top: 0px; width: 245px; left: 834.5px;">
                        <div class="widget">
                            <div class="tabs">
                                <ul class="nav nav-tabs" id="tabs-posts" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#popular" role="tab" aria-controls="popular" aria-selected="true">Populaire</a>
                                    </li>
                                </ul>
                                <div class="tab-content" id="tabs-posts-content">
                                    <div class="tab-pane fade show active" id="popular" role="tabpanel" aria-labelledby="popular-tab">
                                        <div class="post-thumbnail-list">
                                            {% for blog in blogs %}
                                            <div class="post-thumbnail-entry">
                                                <img alt="" src="{{ asset(blog.image) }}">
                                                <div class="post-thumbnail-content">
                                                    <a href="{{ path('showBlog' , {slug : blog.slug}) }}">{{ blog.title | capitalize() }}>{{blog.titleh1 | capitalize()}}</a>
                                                </div>
                                            </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end: Sidebar-->
            </div>
        </div>
    </section>

{#    <div id="featuredImage" style="background-image: url('{{ blog.featuredImage.filepath }}') ; width: 100%;height: 200px;background-size: cover;background-position: center;background-repeat: no-repeat;"></div>#}
{#    <section class="">#}

{#    <div class="entry-content">#}


{#        <br>#}
{#        <h1 style="text-align:center">{{blog.titleh1}}</h1>#}
{#        <br>#}


{#        <div class="container content">#}
{#            {{ blog.displayContent | raw}}#}
{#        </div>#}
{#        <section id="contact">#}
{#            <div class="container">#}
{#                <div class="heading-text text-center heading-section">#}
{#                    <h4 style="font-size: 38px;line-height: 40px;"> Quoi qu'il en soit, optez pour la sécurité et le confort </h4>#}
{#                    <h4> Choisissez MHA-VTC !</h4>#}
{#                </div>#}
{#                <div class="row">#}
{#                    <div class="col-lg-12 text-center">#}
{#                        <a class="btn" href="{{ path('reservation') }}"> Réserver une course </a>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </section>#}
{#    </div>#}
{#    </section>#}
{% endblock %}

templates/mha/home.html.twig
{% extends('mha/fullwidth-base.html.twig') %}
 {% block canonical %}
     <link rel="canonical" href="https://mha-vtc.fr/index.php" />
 {% endblock %}

{% block pageContent %}
    <div id="slider" class="inspiro-slider slider-fullscreen dots-creative" data-fade="true">
        <!-- Slide 1 -->
        <div class="slide kenburns" data-bg-image="{{ asset('/images/5ec78f4653946.png.webp') }}">
            <div class="bg-overlay"></div>
            <div class="container">
                <div id="presentation-text" class="slide-captions text-center text-light">
                    <!-- Captions -->
                    <h1>M.H.A Transport VTC</h1>
                    <p> Nous sommes soucieux de votre confort. </p>
                    <div><a href="{{ path('reservation') }}" class="btn scroll-to">Reserver un trajet</a></div>
                    </span>
                    <!-- end: Captions -->
                </div>
            </div>
        </div>
        <!-- end: Slide 1 -->
    </div>
    <!--end: Inspiro Slider -->
    <!-- WELCOME -->
    <section id="reserver"  style="padding: 150px 0;">
        <div class="container">
            <div class="heading-text text-center heading-section">
                <h2> Réserver un trajet </h2>
                <h4 style="font-size: 22px;"> Un trajet à faire dans Toulouse et son agglomération ? </h4>
                <h4 style="font-size: 22px;"> Réservez une course rapidement et en toute sécurité avec MHA-vtc !</h4>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <a class="btn btn-lg" href="{{ path('reservation')}}">Réserver</a>
                </div>
            </div>
        </div>
    </section>

    <!-- PORTFOLIO -->
    <section class="p-b-0">
        <div class="container" style="padding-bottom: 30px;">
            <div class="heading-text heading-section">
                <h2>Pour tous vos trajets à Toulouse.</h2>
                <span class="lead">Nous prennons en charge tous vos déplacements dans Toulouse et son agglomération. Cela comprends les trajets
                reliant les points importants de la ville tels que l'aéroport ou la gare, mais également les trajets quotidiens en tout genre, vous pouvez
                compter sur nous.</span>
            </div>
        </div>
        <div class="portfolio">
            <!-- Portfolio Items -->
            <div id="portfolio" class="grid-layout portfolio-4-columns" data-margin="0">
                <!-- portfolio item -->
                <div class="portfolio-item img-zoom ct-marketing ct-media ct-branding ct-marketing ct-webdesign">
                    <div class="portfolio-item-wrap">
                        <div class="portfolio-image">
                            <a href="#"><img src="{{ asset('/images/508 gt (1).jpg.webp') }}" alt=""></a>
                        </div>
                        <div class="portfolio-description">
                            <a href="#">
                                <h3>508 GT</h3>
                                <span>Un confort maximum.</span>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- end: portfolio item -->
                <!-- portfolio item -->
                <div class="portfolio-item img-zoom ct-marketing ct-media ct-branding ct-marketing ct-webdesign">
                    <div class="portfolio-item-wrap">
                        <div class="portfolio-image">
                            <a href="#"><img src="{{ asset('/images/5ec78fb10161c.png.webp') }}" alt=""></a>
                        </div>
                        <div class="portfolio-description">
                            <a href="#">
                                <h3>Professionnalisme</h3>
                                <span>Notre savoir faire de chauffeur privé.</span>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- end: portfolio item -->
                <!-- portfolio item -->
                <div class="portfolio-item img-zoom ct-marketing ct-media ct-branding ct-marketing ct-webdesign">
                    <div class="portfolio-item-wrap">
                        <div class="portfolio-image">
                            <a href="#"><img src="{{ asset('/images/5ecb622d1b814.png.webp') }}" alt=""></a>
                        </div>
                        <div class="portfolio-description">
                            <a href="#">
                                <h3>Destination libre</h3>
                                <span>Choisissez où aller à Toulouse.</span>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- end: portfolio item -->
                <!-- portfolio item -->
                <div class="portfolio-item img-zoom ct-marketing ct-media ct-branding ct-marketing ct-webdesign">
                    <div class="portfolio-item-wrap">
                        <div class="portfolio-image">
                            <a href="#"><img src="{{ asset('/images/5ecb627b8b892.png.webp') }}" alt=""></a>
                        </div>
                        <div class="portfolio-description">
                            <a href="#">
                                <h3>Organisation</h3>
                                <span>Ne soyez plus jamais en retard.</span>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- end: portfolio item -->
            </div>
            <!-- end: Portfolio Items -->
        </div>
    </section>
    <!-- end: PORTFOLIO -->
    <!-- WHAT WE DO -->
    <section class="background-grey" id="Apropos">
        <div class="container">
            <div class="heading-text heading-section">
                <h2>Qui sommes nous ? </h2>
                <span class="lead">À propos de M.H.A Transport</span>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div data-animate="fadeInUp" data-animate-delay="0">
                        <div class="icon-box effect medium border center" style="width:100%">
                            <div class="icon"> <a href="#"><i class="fa fa-car"></i></a> </div>
                        </div>
                        <h4>Transport privé Toulouse</h4>

                        <p>M.H.A Transport est une société de VTC mettant à
                            disposition des chauffeurs privés sur Toulouse et son
                            agglomération.
                            Nous vous proposons un service de transport de
                            personnes de qualité à des prix abordables.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div data-animate="fadeInUp" data-animate-delay="200">
                        <div class="icon-box effect medium border center" style="width:100%">
                            <div class="icon"> <a href="#"><i class="fas fa-star"></i></a> </div>
                        </div>
                        <h4>Un service d'exception</h4>
                        <p> Les services
                            proposés concernent aussi bien les particuliers que les
                            entreprises. À bord, nous disposons d'un certain nombre
                            d'avantages : chargeur USB, climatisation, eau, sièges
                            homologués pour enfants, paiement sans contact, gel
                            antibactérien, afin de maximiser votre confort lors du trajet.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div data-animate="fadeInUp" data-animate-delay="400">

                        <div class="icon-box effect medium border center" style="width:100%">
                            <div class="icon"> <a href="#"><i class="fa fa-shield-alt"></i></a> </div>
                        </div>
                        <h4>Votre sécurité est notre préocuppation</h4>
                        <p>En outre, au regard de la crise sanitaire que nous
                            vivons actuellement, les véhicules sont totalement désinfecté
                            après chaque trajet effectué. La sécurité des personnes
                            transportées étant notre priorité, le port du masque est donc
                            obligatoire à la fois pour les personnes transportées que pour
                            les Chauffeurs. Pour permettre à tout le monde de se déplacer
                            en toute sécurité.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- END WHAT WE DO -->

    <!-- COUNTERS -->
    <section class="text-light p-t-150 p-b-150 " data-bg-parallax="{{ asset('/images/5ec78bc256220.png.webp') }}">
        <div class="bg-overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="text-center">
                        <div class="icon"><i class="fa fa-3x fa-road"></i></div>
                        <div class="counter"> <span data-speed="1000" data-refresh-interval="50" data-to="25012" data-from="20000" data-seperator="true"></span> </div>
                        <div class="seperator seperator-small"></div>
                        <p>KMs PARCOURU</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="text-center">
                        <div class="icon"><i class="fa fa-3x  fa-smile-beam"></i></div>
                        <div class="counter"> <span data-speed="1000" data-refresh-interval="42" data-to="2231" data-from="2000" data-seperator="true"></span> </div>
                        <div class="seperator seperator-small"></div>
                        <p>Clients satisfaits </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end: COUNTERS -->
    <section id="contact" style="padding: 100px 0;">
        <div class="container">
            <div class="heading-text text-center heading-section">
                <h2> Contactez nous </h2>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <a class="btn" href="mailto:chauffeur@mha-vtc.fr"> Envoyez nous un mail !</a>
                </div>
            </div>
        </div>
    </section>
    <div id="modalStripBottom" class="modal-strip modal-bottom">
        <div class="container">

            <div class="text-center">
                Réouverture des réservations le 8 Septembre, Nous vous présentons toutes nos excuses pour ce désagrément.
                <div>
                    <a href="#" data-modal="#modalStripBottom" class="btn-modal" style="padding: 10px"><span class="fa fa-times"></span></a>
                </div>
            </div>
        </div>
    </div>


{% endblock %}
{% block javascript %}

{% endblock %}